# Generated by Django 2.2 on 2019-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190413_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject_of_studies',
            field=models.CharField(max_length=100),
        ),
    ]
