# Generated by Django 2.2 on 2019-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Servis Adı')),
                ('priority', models.SmallIntegerField(verbose_name='Öncelik')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
