# Generated by Django 2.2 on 2019-04-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_location_servicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='coupon_code',
        ),
    ]
