# Generated by Django 2.2 on 2019-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicedetail_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('info', models.CharField(max_length=50, verbose_name='İnfo')),
                ('image_url', models.CharField(max_length=255, verbose_name='Fotoğraf')),
                ('latitude', models.CharField(max_length=21, verbose_name='Enlem')),
                ('longitude', models.CharField(max_length=21, verbose_name='Boylam')),
                ('coupon_code', models.CharField(max_length=50, verbose_name='Kupon Kodu')),
                ('status', models.BooleanField(default=True, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
